Fix CSI driver node selector on v1.24+
edgelesssys/constellation-azuredisk-csi-driver pull request #27
Opened 2022-10-14 13:36 UTC by Nirusu

🐛 fix:
Constellation with Kubernetes v1.24+ does have the deprecated master _taint_, but not the master _label_.

This causes the CSI disk driver to never get scheduled onto a node as the node selector defined in the CSI controller tries to search for a node with the master label, which does not exist in the cluster.

This PR fixes this by removing the requirement and solely requiring the control-plane label, as master is deprecated anyway and all our supported releases should already have the control-plane label.

2022-10-14 13:44 UTC, daniel-weisse requested changes
IMO, we should not overwrite the existing charts for v1.0, but generate new ones for the next release.
The deployment issues is easily fixed for the existing chart by specifying `--set controller.runOnMaster=false` during deployment

2022-10-14 14:00 UTC, Nirusu commented
Ah, I did get understand you wrong initially.

Do we want to release this as a new version somewhat soon then, as this affects current deployments? Otherwise we would need to include this fix into the docs for now which would be fugly.

2022-10-14 14:12 UTC, Nirusu commented
Now declared as v1.0.1.

2022-10-14 14:27 UTC, daniel-weisse commented
I don't think changing a default value in the helm chart warrants a new release.
I would keep the changes in `charts/edgeless/latest` for now and not create any packaged charts.

I'm open rebasing and creating a new release for the next upstream release.

2022-10-14 14:30 UTC, Nirusu commented
Problem is if you follow the current docs 1:1, CSI drivers are broken on Kubernetes v1.24+ and this is the default K8s version in Constellation v2.1.0. 

I think it's somewhat a critical issue that should be documented if we don't publish a bug fix release. Otherwise you end up with broken persistent storage on Azure.

2022-10-19 07:30 UTC, Nirusu commented
Since I‘d like to get this done for the Haven reference implementation, my idea would be to generally think about the release scheme for CSI drivers and decide on that.

From what I can tell, the original Azure CSI driver usually bumps the minor version for each release.
If we decide to use the same idea, than bumping the patch version here seems totally fine for me.
If we decide to use an alternating release scheme (e.g. release a new patch version when we rebase the CSI driver on the current state of the Azure CSI driver), than waiting and not releasing anything yet makes sense to me.

However, is bumping latest but not releasing a new release also practise with the official CSI driver?


@daniel-weisse Let me know your thoughts on this. Would like to get this done this week in someway or another. Main thing I care about is having someway that works with the current documentation (which points to latest on main).

2022-10-19 07:46 UTC, daniel-weisse approved these changes

2022-10-19 07:53 UTC, daniel-weisse commented
> CVE-2022-32149: An attacker may cause a denial of service by crafting an Accept-Language header which ParseAcceptLanguage will take significant time to parse.

IMO this is acceptable

2022-10-20 09:51 UTC, Nirusu commented
Guess this should be fixed by rebasing onto the next CSI driver anyway, right?

So 1.0.1 = this fix and then 1.1.0 an upcoming rebase?

Then I would merge this (and see if I can figure out rebasing develop to main again), okay?

2022-10-20 09:58 UTC, merged